pipeline:
  test:
    image: node:9
    commands:
      - npm install
      - npm run test
  sonar:
    image: docker
    privileged: true
    commands:
      - docker run -t -v $(pwd):/root/src --link sonarqube mitch/sonarscanner sonar-scanner 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  build:
    image: node:9
    commands:
      - npm install
      - npm run build
