pipeline:
  build:
    image: node:9
    commands:
      - npm install
      - npm build
  # publish:
  #   image: plugins/docker
  #   repo: eisenxu/realtopper-app
  #   secrets: [ docker_username, docker_password ]
  #   tags:
  #     - latest
  #     - ${DRONE_COMMIT_SHA:0:8}
