pipeline:
  test:
    image: node:9
    commands:
      - npm install
      - npm run test
  sonar:
    image: docker
    commands:
      - sudo docker run -t -v $(pwd):/root/src --link sonarqube newtmitch/sonar-scanner 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  build:
    image: node:9
    commands:
      - npm install
      - npm run build
