pipeline:
  test:
    image: node:9
    commands:
      - npm install
      - npm run test
  sonar:
    image: newtmitch/sonar-scanner
    pull: true
    commands:
      - docker run -ti -v $(pwd):/root/src --link sonarqube newtmitch/sonar-scanner 
  build:
    image: node:9
    commands:
      - npm install
      - npm run build
