pipeline:
  test:
    image: node:9
    commands:
      - npm install
      - npm run test
  sonar:
    image: sonarqube
    pull: true
    commands:
      - sonar-scanner
  build:
    image: node:9
    commands:
      - npm install
      - npm run build
