pipeline:
  test:
    image: node:9
    commands:
      - npm install
      - npm run test
  sonar:
    image: industrieco/sonarqube-server
    commands:
      - sonar-scanner
  build:
    image: node:9
    commands:
      - npm install
      - npm run build
